package rental;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import static javax.persistence.CascadeType.REMOVE;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.AUTO;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

@Entity
public class Car implements Serializable {

    
    /**
     * We deleted the car id generation in the Crc loader in favor of auto generation
     * by the database, this also caused trouble with the sample data generated by JDBC
     */
    @Id
    @GeneratedValue(strategy=AUTO)
    private int id;
    
    /**
     * A car can only have one car type, but a car type can have many
     * instances of cars. The relationship does not have to be
     * bidirectional since the car only needs to access it's type
     */
    @ManyToOne
    private CarType type;
    
    /**
     * Since the To One side is not used a lazy load of the 
     * company will suffice for our use case
     */
    @ManyToOne(fetch=FetchType.LAZY)
    private CarRentalCompany company;
    
    @OneToMany(cascade=REMOVE, mappedBy="car")
    private Set<Reservation> reservations;

    /***************
     * CONSTRUCTOR *
     ***************/
    
    /**
     * Default constructor needed for JPA
     */
    protected Car(){ }    
    
    protected void setCompany(CarRentalCompany company){
        this.company = company;
    }
    
    public Car( CarType type) {
        this.type = type;
        this.reservations = new HashSet<Reservation>();
    }

    /******
     * ID *
     ******/
    
    public int getId() {
    	return id;
    }
    
    /************
     * CAR TYPE *
     ************/
    
    public CarType getType() {
        return type;
    }
	
    public void setType(CarType type) {
            this.type = type;
    }
    
    
    
    /****************
     * RESERVATIONS *
     ****************/

    public boolean isAvailable(Date start, Date end) {
        if(!start.before(end))
            throw new IllegalArgumentException("Illegal given period");

        for(Reservation reservation : reservations) {
            if(reservation.getEndDate().before(start) || reservation.getStartDate().after(end))
                continue;
            return false;
        }
        return true;
    }
    
    public void addReservation(Reservation res) {
        reservations.add(res);
    }
    
    public void removeReservation(Reservation reservation) {
        // equals-method for Reservation is required!
        reservations.remove(reservation);
    }

    public Set<Reservation> getReservations() {
        return reservations;
    }
}